# Generated by Django 5.0.6 on 2024-06-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookufy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='note',
        ),
        migrations.RemoveField(
            model_name='book',
            name='num_of_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='release_year',
        ),
        migrations.AddField(
            model_name='book',
            name='num_of_page',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
