# Generated by Django 5.0.6 on 2024-06-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookufy', '0002_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='book',
            name='is_public_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
